const TEAM_CREATION_TABLE = {
  KR: {
    Index: 'KR',
    '1-1': 'No quality',
    '1-2': 'No quality',
    '1-3': 'No quality',
    '1-4': 'No quality',
    '1-5': 'No quality',
    '1-6': 'No quality',
    '2-2': 'No quality',
    '2-3': 'No quality',
    '2-4': 'No quality',
    '2-5': 'No quality',
    '2-6': 'No quality',
    '3-3': 'No quality',
    '3-4': 'No quality',
    '3-5': 'No quality',
    '3-6': 'No quality',
    '4-4': 'No quality',
    '4-5': 'ELECTRIC•',
    '4-6': 'ELECTRIC•',
    '5-5': 'ELECTRIC•',
    '5-6': 'ELECTRIC•',
    '6-6': 'ELECTRIC',
  },
  PR: {
    Index: 'PR',
    '1-1': 'No quality',
    '1-2': 'No quality',
    '1-3': 'No quality',
    '1-4': 'No quality',
    '1-5': 'No quality',
    '1-6': 'No quality',
    '2-2': 'No quality',
    '2-3': 'No quality',
    '2-4': 'No quality',
    '2-5': 'No quality',
    '2-6': 'No quality',
    '3-3': 'No quality',
    '3-4': 'No quality',
    '3-5': 'No quality',
    '3-6': 'ELECTRIC•',
    '4-4': 'ELECTRIC•',
    '4-5': 'ELECTRIC•',
    '4-6': 'ELECTRIC•',
    '5-5': 'ELECTRIC•',
    '5-6': 'ELECTRIC',
    '6-6': 'ELECTRIC',
  },
  FG: {
    Index: 'FG',
    '1-1': '11-45',
    '1-2': '11-46',
    '1-3': '11-51',
    '1-4': '11-52',
    '1-5': '11-53',
    '1-6': '11-53',
    '2-2': '11-54',
    '2-3': '11-53',
    '2-4': '11-54',
    '2-5': '11-54',
    '2-6': '11-55',
    '3-3': '11-55',
    '3-4': '11-56',
    '3-5': '11-56',
    '3-6': '11-61',
    '4-4': '11-61',
    '4-5': '11-62',
    '4-6': '11-63',
    '5-5': '11-65',
    '5-6': '11-64',
    '6-6': '11-65',
  },
  XP: {
    Index: 'XP',
    '1-1': '11-56',
    '1-2': '11-56',
    '1-3': '11-61',
    '1-4': '11-61',
    '1-5': '11-62',
    '1-6': '11-62',
    '2-2': '11-63',
    '2-3': '11-62',
    '2-4': '11-63',
    '2-5': '11-63',
    '2-6': '11-64',
    '3-3': '11-64',
    '3-4': '11-64',
    '3-5': '11-64',
    '3-6': '11-64',
    '4-4': '11-65',
    '4-5': '11-65',
    '4-6': '11-65',
    '5-5': '11-66',
    '5-6': '11-65',
    '6-6': '11-66',
  },
  XP_2YARD: {
    Index: 'XP_2YARD',
    '1-1': '11-63',
    '1-2': '11-64',
    '1-3': '11-64',
    '1-4': '11-65',
    '1-5': '11-65',
    '1-6': '11-65',
    '2-2': '11-66',
    '2-3': '11-66',
    '2-4': '11-66',
    '2-5': '11-66',
    '2-6': '11-66',
    '3-3': '11-66',
    '3-4': '11-66',
    '3-5': '11-66',
    '3-6': '11-66',
    '4-4': '11-66',
    '4-5': '11-66',
    '4-6': '11-66',
    '5-5': '11-66',
    '5-6': '11-66',
    '6-6': '11-66',
  },
  Prolific: {
    Index: 'Prolific',
    '1-1': 'PROLIFIC',
    '1-2': 'PROLIFIC',
    '1-3': 'PROLIFIC',
    '1-4': 'PROLIFIC',
    '1-5': 'PROLIFIC, SOLID•',
    '1-6': 'PROLIFIC, SOLID•',
    '2-2': 'PROLIFIC, DYNAMIC•',
    '2-3': 'PROLIFIC, DYNAMIC•',
    '2-4': 'PROLIFIC, DYNAMIC•',
    '2-5': 'PROLIFIC, DYNAMIC',
    '2-6': 'PROLIFIC, DYNAMIC',
    '3-3': 'PROLIFIC, DYNAMIC',
    '3-4': 'PROLIFIC, DYNAMIC',
    '3-5': 'PROLIFIC, DYNAMIC•, SOLID',
    '3-6': 'PROLIFIC, DYNAMIC•, SOLID',
    '4-4': 'PROLIFIC, DYNAMIC•, SOLID',
    '4-5': 'PROLIFIC, DYNAMIC, SOLID•',
    '4-6': 'PROLIFIC, DYNAMIC, SOLID•',
    '5-5': 'PROLIFIC, SOLID',
    '5-6': 'PROLIFIC, DYNAMIC, SOLID',
    '6-6': 'PROLIFIC, DYNAMIC•, SOLID•',
  },
  Prolific_Random: {
    Index: 'Prolific_Random',
    '1-1': 'DYNAMIC•, SOLID•',
    '1-2': 'DYNAMIC•, SOLID•',
    '1-3': 'DYNAMIC•, SOLID•',
    '1-4': 'DYNAMIC•, SOLID•',
    '1-5': 'DYNAMIC•',
    '1-6': 'DYNAMIC•',
    '2-2': 'SOLID•',
    '2-3': 'SOLID•',
    '2-4': 'SOLID•',
    '2-5': 'SOLID•',
    '2-6': 'SOLID•',
    '3-3': 'SOLID•',
    '3-4': 'SOLID•',
    '3-5': 'No quality',
    '3-6': 'No quality',
    '4-4': 'No quality',
    '4-5': 'No quality',
    '4-6': 'No quality',
    '5-5': 'DYNAMIC•',
    '5-6': 'No quality',
    '6-6': 'No quality',
  },
  Semi_Prolific: {
    Index: 'Semi_Prolific',
    '1-1': 'PROLIFIC•, POROUS•',
    '1-2': 'PROLIFIC•',
    '1-3': 'PROLIFIC•',
    '1-4': 'PROLIFIC•',
    '1-5': 'PROLIFIC•',
    '1-6': 'PROLIFIC•',
    '2-2': 'PROLIFIC•, SOLID•',
    '2-3': 'PROLIFIC•, SOLID•',
    '2-4': 'PROLIFIC•, DYNAMIC•',
    '2-5': 'PROLIFIC•, DYNAMIC•',
    '2-6': 'PROLIFIC•, DYNAMIC•',
    '3-3': 'PROLIFIC•, DYNAMIC',
    '3-4': 'PROLIFIC•, DYNAMIC',
    '3-5': 'PROLIFIC•, DYNAMIC',
    '3-6': 'PROLIFIC•, SOLID',
    '4-4': 'PROLIFIC•, DYNAMIC, SOLID',
    '4-5': 'PROLIFIC•, DYNAMIC, SOLID',
    '4-6': 'PROLIFIC•, DYNAMIC•, SOLID•',
    '5-5': 'PROLIFIC•, DYNAMIC•, SOLID',
    '5-6': 'PROLIFIC•, DYNAMIC•, SOLID•',
    '6-6': 'PROLIFIC•, DYNAMIC, SOLID•',
  },
  Semi_Prolific_Random: {
    Index: 'Semi_Prolific_Random',
    '1-1': 'DYNAMIC•, SOLID•',
    '1-2': 'DYNAMIC•, SOLID•',
    '1-3': 'DYNAMIC•, SOLID•',
    '1-4': 'DYNAMIC•, SOLID•',
    '1-5': 'DYNAMIC•, SOLID•',
    '1-6': 'DYNAMIC•, SOLID•',
    '2-2': 'DYNAMIC•',
    '2-3': 'DYNAMIC•',
    '2-4': 'SOLID•',
    '2-5': 'SOLID•',
    '2-6': 'SOLID•',
    '3-3': 'SOLID•',
    '3-4': 'SOLID•',
    '3-5': 'SOLID•',
    '3-6': 'DYNAMIC•',
    '4-4': 'No quality',
    '4-5': 'No quality',
    '4-6': 'No quality',
    '5-5': 'No quality',
    '5-6': 'No quality',
    '6-6': 'No quality',
  },
  Dull: {
    Index: 'Dull',
    '1-1': 'DULL',
    '1-2': 'DULL',
    '1-3': 'DULL',
    '1-4': 'DULL',
    '1-5': 'DULL, POROUS•',
    '1-6': 'DULL, POROUS•',
    '2-2': 'DULL, ERRATIC•',
    '2-3': 'DULL, ERRATIC•',
    '2-4': 'DULL, ERRATIC•',
    '2-5': 'DULL, ERRATIC',
    '2-6': 'DULL, ERRATIC',
    '3-3': 'DULL, ERRATIC',
    '3-4': 'DULL, ERRATIC',
    '3-5': 'DULL, ERRATIC•, POROUS',
    '3-6': 'DULL, ERRATIC•, POROUS',
    '4-4': 'DULL, ERRATIC•, POROUS',
    '4-5': 'DULL, ERRATIC, POROUS•',
    '4-6': 'DULL, ERRATIC, POROUS•',
    '5-5': 'DULL, POROUS',
    '5-6': 'DULL, ERRATIC, POROUS',
    '6-6': 'DULL, SOLID•',
  },
  Dull_Random: {
    Index: 'Dull_Random',
    '1-1': 'ERRATIC•, POROUS•',
    '1-2': 'ERRATIC•, POROUS•',
    '1-3': 'ERRATIC•, POROUS•',
    '1-4': 'ERRATIC•, POROUS•',
    '1-5': 'ERRATIC•',
    '1-6': 'ERRATIC•',
    '2-2': 'POROUS•',
    '2-3': 'POROUS•',
    '2-4': 'POROUS•',
    '2-5': 'POROUS•',
    '2-6': 'POROUS•',
    '3-3': 'POROUS•',
    '3-4': 'POROUS•',
    '3-5': 'No quality',
    '3-6': 'No quality',
    '4-4': 'No quality',
    '4-5': 'No quality',
    '4-6': 'No quality',
    '5-5': 'ERRATIC•',
    '5-6': 'No quality',
    '6-6': 'ERRATIC•, POROUS•',
  },
  Semi_Dull: {
    Index: 'Semi_Dull',
    '1-1': 'DULL•',
    '1-2': 'DULL•',
    '1-3': 'DULL•',
    '1-4': 'DULL•',
    '1-5': 'DULL•',
    '1-6': 'DULL•',
    '2-2': 'DULL•, POROUS•',
    '2-3': 'DULL•, POROUS•',
    '2-4': 'DULL•, ERRATIC•',
    '2-5': 'DULL•, ERRATIC•',
    '2-6': 'DULL•, ERRATIC•',
    '3-3': 'DULL•, ERRATIC',
    '3-4': 'DULL•, ERRATIC',
    '3-5': 'DULL•, ERRATIC',
    '3-6': 'DULL•, POROUS',
    '4-4': 'DULL•, DYNAMIC•',
    '4-5': 'DULL•, ERRATIC, POROUS•',
    '4-6': 'DULL•, ERRATIC•, POROUS•',
    '5-5': 'DULL•, ERRATIC, SOLID',
    '5-6': 'DULL•, SOLID',
    '6-6': 'DULL•, SOLID•',
  },
  Semi_Dull_Random: {
    Index: 'Semi_Dull_Random',
    '1-1': 'ERRATIC•, POROUS•',
    '1-2': 'ERRATIC•, POROUS•',
    '1-3': 'ERRATIC•, POROUS•',
    '1-4': 'ERRATIC•, POROUS•',
    '1-5': 'ERRATIC•, POROUS•',
    '1-6': 'ERRATIC•, POROUS•',
    '2-2': 'ERRATIC•',
    '2-3': 'ERRATIC•',
    '2-4': 'POROUS•',
    '2-5': 'POROUS•',
    '2-6': 'POROUS•',
    '3-3': 'POROUS•',
    '3-4': 'POROUS•',
    '3-5': 'POROUS•',
    '3-6': 'ERRATIC•',
    '4-4': 'ERRATIC•, POROUS•',
    '4-5': 'No quality',
    '4-6': 'No quality',
    '5-5': 'POROUS•',
    '5-6': 'ERRATIC•, POROUS•',
    '6-6': 'ERRATIC•, POROUS•',
  },
  Staunch: {
    Index: 'Staunch',
    '1-1': 'STAUNCH',
    '1-2': 'STAUNCH',
    '1-3': 'STAUNCH',
    '1-4': 'STAUNCH',
    '1-5': 'STAUNCH, STIFF•',
    '1-6': 'STAUNCH, STIFF•',
    '2-2': 'STAUNCH, STIFF',
    '2-3': 'STAUNCH, STIFF',
    '2-4': 'STAUNCH, STIFF',
    '2-5': 'STAUNCH, STIFF',
    '2-6': 'STAUNCH, PUNISHING•',
    '3-3': 'STAUNCH, PUNISHING•',
    '3-4': 'STAUNCH, PUNISHING',
    '3-5': 'STAUNCH, PUNISHING',
    '3-6': 'STAUNCH, STIFF, PUNISHING•',
    '4-4': 'STAUNCH, STIFF•, PUNISHING•',
    '4-5': 'STAUNCH, STIFF•, PUNISHING•',
    '4-6': 'STAUNCH, STIFF, PUNISHING',
    '5-5': 'STAUNCH, STIFF, PUNISHING•',
    '5-6': 'STAUNCH, STIFF, PUNISHING',
    '6-6': 'STAUNCH, STIFF, PUNISHING',
  },
  Staunch_Random: {
    Index: 'Staunch_Random',
    '1-1': 'STIFF•, PUNISHING•',
    '1-2': 'STIFF•, PUNISHING•',
    '1-3': 'STIFF•, PUNISHING•',
    '1-4': 'STIFF•, PUNISHING•',
    '1-5': 'PUNISHING•',
    '1-6': 'PUNISHING•',
    '2-2': 'PUNISHING•',
    '2-3': 'PUNISHING•',
    '2-4': 'PUNISHING•',
    '2-5': 'PUNISHING•',
    '2-6': 'STIFF•',
    '3-3': 'STIFF•',
    '3-4': 'STIFF•',
    '3-5': 'STIFF•',
    '3-6': 'No quality',
    '4-4': 'No quality',
    '4-5': 'No quality',
    '4-6': 'No quality',
    '5-5': 'No quality',
    '5-6': 'No quality',
    '6-6': 'No quality',
  },
  Semi_Staunch: {
    Index: 'Semi_Staunch',
    '1-1': 'STAUNCH•, MILD•',
    '1-2': 'STAUNCH•',
    '1-3': 'STAUNCH•',
    '1-4': 'STAUNCH•',
    '1-5': 'STAUNCH•',
    '1-6': 'STAUNCH•',
    '2-2': 'STAUNCH•',
    '2-3': 'STAUNCH•',
    '2-4': 'STAUNCH•',
    '2-5': 'STAUNCH•, STIFF•',
    '2-6': 'STAUNCH•, STIFF•',
    '3-3': 'STAUNCH•, STIFF•',
    '3-4': 'STAUNCH•, STIFF',
    '3-5': 'STAUNCH•, STIFF',
    '3-6': 'STAUNCH•, PUNISHING•',
    '4-4': 'STAUNCH•, STIFF, PUNISHING•',
    '4-5': 'STAUNCH•, PUNISHING',
    '4-6': 'STAUNCH•, STIFF•, PUNISHING•',
    '5-5': 'STAUNCH•, STIFF•, PUNISHING',
    '5-6': 'STAUNCH•, STIFF•, PUNISHING•',
    '6-6': 'STAUNCH•, STIFF, PUNISHING',
  },
  Semi_Staunch_Random: {
    Index: 'Semi_Staunch_Random',
    '1-1': 'STIFF•, PUNISHING•',
    '1-2': 'STIFF•, PUNISHING•',
    '1-3': 'STIFF•, PUNISHING•',
    '1-4': 'STIFF•, PUNISHING•',
    '1-5': 'STIFF•, PUNISHING•',
    '1-6': 'STIFF•, PUNISHING•',
    '2-2': 'STIFF•, PUNISHING•',
    '2-3': 'STIFF•, PUNISHING•',
    '2-4': 'STIFF•, PUNISHING•',
    '2-5': 'PUNISHING•',
    '2-6': 'PUNISHING•',
    '3-3': 'PUNISHING•',
    '3-4': 'PUNISHING•',
    '3-5': 'PUNISHING•',
    '3-6': 'STIFF•',
    '4-4': 'No quality',
    '4-5': 'STIFF•',
    '4-6': 'No quality',
    '5-5': 'No quality',
    '5-6': 'No quality',
    '6-6': 'No quality',
  },
  Inept: {
    Index: 'Inept',
    '1-1': 'INEPT',
    '1-2': 'INEPT',
    '1-3': 'INEPT, SOFT',
    '1-4': 'INEPT, SOFT',
    '1-5': 'INEPT, SOFT',
    '1-6': 'INEPT, SOFT',
    '2-2': 'INEPT, SOFT',
    '2-3': 'INEPT, SOFT•',
    '2-4': 'INEPT, SOFT•',
    '2-5': 'INEPT, MILD',
    '2-6': 'INEPT, MILD•',
    '3-3': 'INEPT, SOFT, MILD•',
    '3-4': 'INEPT, SOFT•, MILD•',
    '3-5': 'INEPT, SOFT•, MILD•',
    '3-6': 'INEPT, SOFT•, MILD',
    '4-4': 'INEPT, SOFT, MILD•',
    '4-5': 'INEPT, SOFT, MILD',
    '4-6': 'INEPT, SOFT, MILD',
    '5-5': 'INEPT, SOFT, MILD',
    '5-6': 'INEPT, SOFT, MILD',
    '6-6': 'INEPT, SOFT, MILD',
  },
  Inept_Random: {
    Index: 'Inept_Random',
    '1-1': 'SOFT•, MILD•',
    '1-2': 'SOFT•, MILD•',
    '1-3': 'MILD•',
    '1-4': 'MILD•',
    '1-5': 'MILD•',
    '1-6': 'MILD•',
    '2-2': 'MILD•',
    '2-3': 'MILD•',
    '2-4': 'MILD•',
    '2-5': 'SOFT•',
    '2-6': 'SOFT•',
    '3-3': 'No quality',
    '3-4': 'No quality',
    '3-5': 'No quality',
    '3-6': 'No quality',
    '4-4': 'No quality',
    '4-5': 'No quality',
    '4-6': 'No quality',
    '5-5': 'No quality',
    '5-6': 'No quality',
    '6-6': 'No quality',
  },
  Semi_Inept: {
    Index: 'Semi_Inept',
    '1-1': 'INEPT•',
    '1-2': 'INEPT•',
    '1-3': 'INEPT•',
    '1-4': 'INEPT•',
    '1-5': 'INEPT•',
    '1-6': 'INEPT•',
    '2-2': 'INEPT•',
    '2-3': 'INEPT•',
    '2-4': 'INEPT•, SOFT•',
    '2-5': 'INEPT•, SOFT•',
    '2-6': 'INEPT•, SOFT•',
    '3-3': 'INEPT•, MILD•',
    '3-4': 'INEPT•, SOFT',
    '3-5': 'INEPT•, SOFT',
    '3-6': 'INEPT•, SOFT',
    '4-4': 'INEPT•, MILD',
    '4-5': 'INEPT•, SOFT•, MILD•',
    '4-6': 'INEPT•, SOFT, MILD•',
    '5-5': 'INEPT•, MILD',
    '5-6': 'INEPT•, SOFT•, MILD',
    '6-6': 'INEPT•, SOFT, MILD',
  },
  Semi_Inept_Random: {
    Index: 'Semi_Inept_Random',
    '1-1': 'SOFT•, MILD•',
    '1-2': 'SOFT•, MILD•',
    '1-3': 'SOFT•, MILD•',
    '1-4': 'SOFT•, MILD•',
    '1-5': 'SOFT•, MILD•',
    '1-6': 'SOFT•, MILD•',
    '2-2': 'SOFT•, MILD•',
    '2-3': 'SOFT•, MILD•',
    '2-4': 'MILD•',
    '2-5': 'MILD•',
    '2-6': 'MILD•',
    '3-3': 'SOFT•',
    '3-4': 'MILD•',
    '3-5': 'MILD•',
    '3-6': 'MILD•',
    '4-4': 'SOFT•',
    '4-5': 'No quality',
    '4-6': 'No quality',
    '5-5': 'SOFT•',
    '5-6': 'No quality',
    '6-6': 'No quality',
  },
};
const COACH_CREATION_TABLE = {
  '1-1': {
    condition: 'savvy_ownership',
    on: { result: 'B' },
    off: { result: 'D' },
  },
  '1-2': {
    condition: 'front_office_grade_a',
    on: { result: 'C' },
    off: { result: 'D' },
  },
  '1-3': {
    condition: 'front_office_grade_b_or_better',
    on: { result: 'C' },
    off: { result: 'D' },
  },
  '1-4': {
    condition: 'savvy_ownership',
    on: { result: 'A' },
    off: { result: 'C' },
  },
  '1-5': { result: 'C' },
  '1-6': {
    condition: 'front_office_grade_c_or_lower',
    on: { result: 'D' },
    off: { result: 'C' },
  },
  '2-2': { result: 'C' },
  '2-3': {
    condition: 'front_office_grade_a',
    on: { result: 'B' },
    off: { result: 'C' },
  },
  '2-4': {
    condition: 'front_office_grade_d',
    on: { result: 'D' },
    off: { result: 'C' },
  },
  '2-5': {
    condition: 'front_office_grade_b_or_better',
    on: { result: 'B' },
    off: { result: 'C' },
  },
  '2-6': {
    condition: 'meddling_ownership',
    on: { result: 'D' },
    off: { result: 'B' },
  },
  '3-3': { result: 'B' },
  '3-4': {
    condition: 'front_office_grade_a',
    on: { result: 'A' },
    off: { result: 'B' },
  },
  '3-5': {
    condition: 'front_office_grade_d',
    on: { result: 'C' },
    off: { result: 'B' },
  },
  '3-6': { result: 'B' },
  '4-4': {
    condition: 'meddling_ownership',
    on: { result: 'C' },
    off: { result: 'A' },
  },
  '4-5': { result: 'B' },
  '4-6': {
    condition: 'front_office_grade_c_or_lower',
    on: { result: 'C' },
    off: { result: 'B' },
  },
  '5-5': { result: 'A' },
  '5-6': {
    condition: 'front_office_grade_d',
    on: { result: 'B' },
    off: { result: 'A' },
  },
  '6-6': { result: 'A' },
};
const QUALITY_ARRAY = [
  {
    key: 'RELIABLE',
    srs_value: 1,
    text: 'RELIABLE',
    tr_value: 1,
    offense: true,
    defense: false,
    category: 'INT',
    order: 1,
  },
  {
    key: 'SEMI_RELIABLE',
    srs_value: 0.5,
    text: 'RELIABLE•',
    tr_value: 0.5,
    offense: true,
    defense: false,
    category: 'INT',
    order: 2,
  },
  {
    key: 'SEMI_SHAKY',
    srs_value: -0.5,
    text: 'SHAKY•',
    tr_value: -0.5,
    offense: true,
    defense: false,
    category: 'INT',
    order: 3,
  },
  {
    key: 'SHAKY',
    srs_value: -1,
    text: 'SHAKY',
    tr_value: -1,
    offense: true,
    defense: false,
    category: 'INT',
    order: 4,
  },
  {
    key: 'SECURE',
    srs_value: 1,
    text: 'SECURE',
    tr_value: 1,
    offense: true,
    defense: false,
    category: 'FUM',
    order: 5,
  },
  {
    key: 'SEMI_SECURE',
    srs_value: 0.5,
    text: 'SECURE•',
    tr_value: 0.5,
    offense: true,
    defense: false,
    category: 'FUM',
    order: 6,
  },
  {
    key: 'SEMI_CLUMSY',
    srs_value: -0.5,
    text: 'CLUMSY•',
    tr_value: -0.5,
    offense: true,
    defense: false,
    category: 'FUM',
    order: 7,
  },
  {
    key: 'CLUMSY',
    srs_value: -1,
    text: 'CLUMSY',
    tr_value: -1,
    offense: true,
    defense: false,
    category: 'FUM',
    order: 8,
  },
  {
    key: 'DISCIPLINED',
    srs_value: 1,
    text: 'DISCIPLINED',
    tr_value: 1,
    offense: true,
    defense: true,
    category: 'PEN',
    order: 9,
  },
  {
    key: 'SEMI_DISCIPLINED',
    srs_value: 0.5,
    text: 'DISCIPLINED•',
    tr_value: 0.5,
    offense: true,
    defense: true,
    category: 'PEN',
    order: 10,
  },
  {
    key: 'SEMI_UNDISCIPLINED',
    srs_value: -0.5,
    text: 'UNDISCIPLINED•',
    tr_value: -0.5,
    offense: true,
    defense: true,
    category: 'PEN',
    order: 11,
  },
  {
    key: 'UNDISCIPLINED',
    srs_value: -1,
    text: 'UNDISCIPLINED',
    tr_value: -1,
    offense: true,
    defense: true,
    category: 'PEN',
    order: 12,
  },
  {
    key: 'DYNAMIC',
    srs_value: 1,
    text: 'DYNAMIC',
    tr_value: 1,
    offense: true,
    defense: false,
    category: 'BALL_CONTROL',
    order: 0,
  },
  {
    key: 'SEMI_DYNAMIC',
    srs_value: 0.5,
    text: 'DYNAMIC•',
    tr_value: 0.5,
    offense: true,
    defense: false,
    category: 'BALL_CONTROL',
    order: 0,
  },
  {
    key: 'SEMI_ERRATIC',
    srs_value: -0.5,
    text: 'ERRATIC•',
    tr_value: -0.5,
    offense: true,
    defense: false,
    category: 'BALL_CONTROL',
    order: 0,
  },
  {
    key: 'ERRATIC',
    srs_value: -1,
    text: 'ERRATIC',
    tr_value: -1,
    offense: true,
    defense: false,
    category: 'BALL_CONTROL',
    order: 0,
  },
  {
    key: 'EFFICIENT',
    srs_value: 4,
    text: 'EFFICIENT',
    tr_value: 2,
    offense: true,
    defense: false,
    category: 'EFFICIENCY',
    order: 0,
  },
  {
    key: 'SEMI_EFFICIENT',
    srs_value: 2,
    text: 'EFFICIENT•',
    tr_value: 1,
    offense: true,
    defense: false,
    category: 'EFFICIENCY',
    order: 0,
  },
  {
    key: 'SEMI_INEFFICIENT',
    srs_value: -2,
    text: 'INEFFICIENT•',
    tr_value: -1,
    offense: true,
    defense: false,
    category: 'EFFICIENCY',
    order: 0,
  },
  {
    key: 'INEFFICIENT',
    srs_value: -4,
    text: 'INEFFICIENT',
    tr_value: -2,
    offense: true,
    defense: false,
    category: 'EFFICIENCY',
    order: 0,
  },
  {
    key: 'SOLID',
    srs_value: 1,
    text: 'SOLID',
    tr_value: 1,
    offense: true,
    defense: false,
    category: 'SACKS',
    order: 0,
  },
  {
    key: 'SEMI_SOLID',
    srs_value: 0.5,
    text: 'SOLID•',
    tr_value: 0.5,
    offense: true,
    defense: false,
    category: 'SACKS',
    order: 0,
  },
  {
    key: 'SEMI_POROUS',
    srs_value: -0.5,
    text: 'POROUS•',
    tr_value: -0.5,
    offense: true,
    defense: false,
    category: 'SACKS',
    order: 0,
  },
  {
    key: 'POROUS',
    srs_value: -1,
    text: 'POROUS',
    tr_value: -1,
    offense: true,
    defense: false,
    category: 'SACKS',
    order: 0,
  },
  {
    key: 'PROLIFIC',
    srs_value: 4,
    text: 'PROLIFIC',
    tr_value: 4,
    offense: true,
    defense: false,
    category: 'SCORING',
    order: 0,
  },
  {
    key: 'SEMI_PROLIFIC',
    srs_value: 2,
    text: 'PROLIFIC•',
    tr_value: 2,
    offense: true,
    defense: false,
    category: 'SCORING',
    order: 0,
  },
  {
    key: 'SEMI_DULL',
    srs_value: -2,
    text: 'DULL•',
    tr_value: -2,
    offense: true,
    defense: false,
    category: 'SCORING',
    order: 0,
  },
  {
    key: 'DULL',
    srs_value: -4,
    text: 'DULL',
    tr_value: -4,
    offense: true,
    defense: false,
    category: 'SCORING',
    order: 0,
  },
  {
    key: 'AGGRESSIVE',
    srs_value: 1,
    text: 'AGGRESSIVE',
    tr_value: 1,
    offense: false,
    defense: true,
    category: 'INT',
    order: 1,
  },
  {
    key: 'SEMI_AGGRESSIVE',
    srs_value: 0.5,
    text: 'AGGRESSIVE•',
    tr_value: 0.5,
    offense: false,
    defense: true,
    category: 'INT',
    order: 2,
  },
  {
    key: 'SEMI_MEEK',
    srs_value: -0.5,
    text: 'MEEK•',
    tr_value: -0.5,
    offense: false,
    defense: true,
    category: 'INT',
    order: 3,
  },
  {
    key: 'MEEK',
    srs_value: -1,
    text: 'MEEK',
    tr_value: -1,
    offense: false,
    defense: true,
    category: 'INT',
    order: 4,
  },
  {
    key: 'ACTIVE',
    srs_value: 1,
    text: 'ACTIVE',
    tr_value: 1,
    offense: false,
    defense: true,
    category: 'FUM',
    order: 5,
  },
  {
    key: 'SEMI_ACTIVE',
    srs_value: 0.5,
    text: 'ACTIVE•',
    tr_value: 0.5,
    offense: false,
    defense: true,
    category: 'FUM',
    order: 6,
  },
  {
    key: 'SEMI_PASSIVE',
    srs_value: -0.5,
    text: 'PASSIVE•',
    tr_value: -0.5,
    offense: false,
    defense: true,
    category: 'FUM',
    order: 7,
  },
  {
    key: 'PASSIVE',
    srs_value: -1,
    text: 'PASSIVE',
    tr_value: -1,
    offense: false,
    defense: true,
    category: 'FUM',
    order: 8,
  },
  {
    key: 'STIFF',
    srs_value: 1,
    text: 'STIFF',
    tr_value: 1,
    offense: false,
    defense: true,
    category: 'BALL_CONTROL',
    order: 0,
  },
  {
    key: 'SEMI_STIFF',
    srs_value: 0.5,
    text: 'STIFF•',
    tr_value: 0.5,
    offense: false,
    defense: true,
    category: 'BALL_CONTROL',
    order: 0,
  },
  {
    key: 'SEMI_SOFT',
    srs_value: -0.5,
    text: 'SOFT•',
    tr_value: -0.5,
    offense: false,
    defense: true,
    category: 'BALL_CONTROL',
    order: 0,
  },
  {
    key: 'SOFT',
    srs_value: -1,
    text: 'SOFT',
    tr_value: -1,
    offense: false,
    defense: true,
    category: 'BALL_CONTROL',
    order: 0,
  },
  {
    key: 'PUNISHING',
    srs_value: 1,
    text: 'PUNISHING',
    tr_value: 1,
    offense: false,
    defense: true,
    category: 'SACKS',
    order: 0,
  },
  {
    key: 'SEMI_PUNISHING',
    srs_value: 0.5,
    text: 'PUNISHING•',
    tr_value: 0.5,
    offense: false,
    defense: true,
    category: 'SACKS',
    order: 0,
  },
  {
    key: 'SEMI_MILD',
    srs_value: -0.5,
    text: 'MILD•',
    tr_value: -0.5,
    offense: false,
    defense: true,
    category: 'SACKS',
    order: 0,
  },
  {
    key: 'MILD',
    srs_value: -1,
    text: 'MILD',
    tr_value: -1,
    offense: false,
    defense: true,
    category: 'SACKS',
    order: 0,
  },
  {
    key: 'STAUNCH',
    srs_value: 4,
    text: 'STAUNCH',
    tr_value: 4,
    offense: false,
    defense: true,
    category: 'SCORING',
    order: 0,
  },
  {
    key: 'SEMI_STAUNCH',
    srs_value: 2,
    text: 'STAUNCH•',
    tr_value: 2,
    offense: false,
    defense: true,
    category: 'SCORING',
    order: 0,
  },
  {
    key: 'SEMI_INEPT',
    srs_value: -2,
    text: 'INEPT•',
    tr_value: -2,
    offense: false,
    defense: true,
    category: 'SCORING',
    order: 0,
  },
  {
    key: 'INEPT',
    srs_value: -4,
    text: 'INEPT',
    tr_value: -4,
    offense: false,
    defense: true,
    category: 'SCORING',
    order: 0,
  },
  {
    key: 'NO_QUALITY',
    srs_value: 0,
    text: 'No quality',
    tr_value: 0,
    offense: false,
    defense: false,
    category: '',
    order: 0,
  },
  {
    key: 'SEMI_ELECTRIC',
    srs_value: 0.5,
    text: 'ELECTRIC•',
    tr_value: 0,
    offense: false,
    defense: false,
    category: '',
    order: 0,
  },
  {
    key: 'ELECTRIC',
    srs_value: 1,
    text: 'ELECTRIC',
    tr_value: 0,
    offense: false,
    defense: false,
    category: '',
    order: 0,
  },
];